version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123
      - MSSQL_ENCRYPT=OFF
    ports:
      - 1433:1433
    volumes:
      - .\DockerData :/var/opt/mssql/data
